package Functionalitate.Enumerari;

public enum Discipline {
    PROGRAMARE_PROCEDURALA("Programare procedurala"),
    STRUCTURA_FUNCTII("Structura si functii calculator"),
    INFORMATICA("Informatica"),
    CREARE_SITE_WEB("Creare site Web"),
    DESIGN_UI_UX("Design UI/UX"),
    POO("POO"),
    IMPLEMENTARE_SQL("Implementare limbaj SQL"),
    SECURITATEA_INFORMATIEI("Securitatea informatiei"),
    TIC("TIC"),
    DACTILOGRAFIERE("Dactilografiere computerizata"),
    ECHIPAMENTE_BIROU("Echipamente de birou"),
    DEZVOLTARE_APLICATII_WEB("Dezvoltare aplicatii Web"),
    ADMINISTRARE_WEB_SERVER("Administrare Web server"),
    DEZVOLTARE_ANIMATII_WEB("Dezvoltare animatii Web"),
    PROGRAMARE_APLICATII_MOBILE("Programare aplicatii mobile"),
    PROGRAMARE_VIZUALA("Programare vizuala"),
    PROGRAMARE_CLIENT_SIDE("Programare client-side web"),
    ADMINISTRARE_RC("Administrare RC"),
    ELABORARE_APLICATII_NET("Elaborare aplicatii .NET"),
    DEZVOLTARE_APLICATII_DESKTOP("Dezvoltare aplicatii desktop"),
    TESTAREA_APLICATIILOR("Testarea aplicatiilor"),
    DEZVOLTARE_APLICATII_MOBILE("Dezvoltare aplicatii mobile"),
    MANAGEMENT_PROIECTE_SOFTWARE("Management proiecte software"),
    BAZE_LEGISLATIE("Baze legislatie in domeniu"),
    SECURITATEA_MUNCII("Securitatea muncii"),
    LIMBAJ_STRAIN_TIC("Limbaj strain aplicat in TIC"),
    PRACTICA_CONTABILA("Practica contabila"),
    AUDIT_FINANCIAR("Audit situatii financiare"),
    PRETURI_TARIFE("Preturi si tarife"),
    ANALIZA_FINANCIARA("Analiza situatiei financiare"),
    CONTABILITATE_FISCALA("Contabilitate fiscala"),
    TICONT("TICont"),
    FIRMA_EXERCITIU("Firma de exercitiu"),
    CONTABILITATE_EXPLOATARE("Contabilitate activitati exploatare"),
    MARKETING("Marketing"),
    SISTEM_DOCUMENTARE("Sistem documentare contabila"),
    MACROECONOMIE("Macroeconomie"),
    BAZELE_CONTABILITATII("Bazele contabilitatii"),
    TEHNICI_COMUNICARE("Tehnici de comunicare"),
    BAZE_ANTREPRENORIAT("Baze antreprenoriat"),
    ECONOMIE_APLICATA("Economie aplicata"),
    CORESPONDENTA_AFACERI("Corespondenta de afaceri"),
    DREPT_FINANCIAR("Drept financiar fiscal"),
    ASISTENTA_MANAGERIALA("Asistenta manageriala si secretariat"),
    ADMINISTRATIE_PUBLICA("Administratie publica"),
    MANAGEMENTUL_PROIECTELOR("Managementul proiectelor"),
    MANAGEMENT_RESURSE_UMANE("Management resurse umane"),
    ARHIVARE_DOCUMENTARE("Arhivare si documentare"),
    DREPT_AFACERI("Drept afaceri"),
    DREPT_ADMINISTRATIV("Drept administrativ"),
    DREPT_CONSTITUTIONAL("Drept constitutional"),
    DREPTUL_FAMILIEI("Dreptul familiei"),
    PSIHOLOGIE_SOCIALA("Psihologie sociala economica"),
    ETICA_PROFESIONALA("Etica profesionala"),
    ETICA_DEONTOLOGIE("Etica si deontologie profesionala"),
    LIMBAJ_MODERN_ADM("Limbaj modern aplicat in st.adm."),
    LIMBA_ENGLEZA("Limba engleza"),
    LIMBA_FRANCEZA("Limba franceza"),
    LIMBA_STRAINA_DOMENIU("Limba straina aplicata in domeniu"),
    MATEMATICA("Matematica"),
    ISTORIA("Istoria"),
    EDUCATIE_SOCIETATE("Educatie pentru societate"),
    CULTURA_COMUNICARII("Cultura comunicarii"),
    ORA_DIRIGENTIE("Ora de dirigentie"),
    MOD_SANATOS_VIATA("Decizii privind modul sanatos de viata"),
    LIMBA_ROMANA("Limba si literatura romana"),
    LITERATURA_UNIVERSALA("Literatura universala"),
    FIZICA("Fizica"),
    CHIMIA("Chimia"),
    BIOLOGIA("Biologia"),
    GEOGRAFIA("Geografia"),
    EDUCATIE_FIZICA("Educatie fizica");


    private final String denumire;
    Discipline(String d){
        denumire=d;
    }
    public String getDenumire() {
        return denumire;
    }
}
