CREATE TABLE specialitati (
    id SERIAL PRIMARY KEY,
    nume VARCHAR(50),
    prefix VARCHAR(2)
);
INSERT INTO specialitati (nume, prefix) VALUES
('Programare', 'P'),
('Contabilitate', 'C'),
('Aplicatii Web', 'W'),
('Jurisprudenta', 'J'),
('Administrare BD', 'B'),
('Operator', 'O'),
('Retele', 'R'),
('Secretariat', 'S');
CREATE TABLE grupe (
    id SERIAL PRIMARY KEY,
    an INT,
    clasa INT,
    nr_grupa INT,
    id_specialitate INT,
    grupa VARCHAR(10),
    FOREIGN KEY (id_specialitate) REFERENCES specialitati(id)
);
INSERT INTO grupe (an, clasa, nr_grupa, id_specialitate, grupa) VALUES
(24, 3, 1, 3, 'W-2331'),
(24, 2, 2, 2, 'C-2422'),
(22, 4, 2, 4, 'J-2242'),
(25, 1, 1, 2, 'C-2511'),
(23, 4, 1, 5, 'B-2341'),
(25, 1, 3, 6, 'O-2513'),
(24, 2, 1, 1, 'P-2421'),
(23, 3, 2, 7, 'R-2332'),
(24, 2, 3, 1, 'P-2423'),
(25, 1, 4, 1, 'P-2514');

CREATE TABLE studenti (
    id SERIAL PRIMARY KEY,
    nume VARCHAR(50),
    prenume VARCHAR(50),
    id_grupa INT,
    poza VARCHAR(255),
    FOREIGN KEY (id_grupa) REFERENCES grupe(id)
);
INSERT INTO studenti (nume, prenume, id_grupa) VALUES
('Bogza', 'Daniel', 7),
('Enachi', 'Liviu', 7),
('Sclifos', 'Ana', 7),
('Stanca', 'Mihail', 7),
('Cozma', 'Ion', 7),
('Dogari', 'Elena', 9),
('Cascaval', 'Vlad', 9),
('Ivanciuc', 'Vadim', 9),
('Botnari', 'Daniel', 9),
('Tulei', 'Grigore', 9),
('Cretu', 'Stefan', 10),
('Ceban', 'Vlad', 10),
('Tricolici', 'Daria', 10),
('Ciumac', 'Andreea', 10),
('Roica', 'Nicolae', 10),
('Zamostean', 'Nicolae', 1),
('Oboroceanu', 'Ion', 1),
('Bors', 'Patricia', 1),
('Ixari', 'Madalina', 1),
('Cotofan', 'Nicoleta', 1),
('Chiochiu', 'Andrei', 8),
('Pascaru', 'Maria', 8),
('Moraru', 'Alexandru', 8),
('Harea', 'Cristina', 8),
('Russu', 'Ion', 8),
('Grosu', 'Elena', 2),
('Lazari', 'Dumitru', 2),
('Grama', 'Ioana', 2),
('Baciu', 'Andrei', 2),
('Spataru', 'Natalia', 2),
('Rotaru', 'Mihai', 4),
('Ciobanu', 'Ana', 4),
('Draghici', 'Alexandru', 4),
('Ene', 'Maria', 4),
('Farcas', 'Ion', 4),
('Grigore', 'Andreea', 3),
('Hristea', 'Bogdan', 3),
('Iordache', 'Cristina', 3),
('Jora', 'Eduard', 3),
('Kelemen', 'Florina', 3),
('Lungu', 'George', 5),
('Manea', 'Ioana', 5),
('Niculescu', 'Andrei', 5),
('Olteanu', 'Elena', 5),
('Petrescu', 'Mihai', 5),
('Radulescu', 'Ana', 6),
('Sava', 'Alexandru', 6),
('Tanase', 'Maria', 6),
('Ungureanu', 'Ion', 6),
('Dogaru', 'Andreea', 6);


CREATE TABLE note (
    id SERIAL PRIMARY KEY,
    id_student INT,
    nota INT,
    disciplina VARCHAR(50),
    FOREIGN KEY (id_student) REFERENCES studenti(id)
);
INSERT INTO note (id_student, nota, disciplina) VALUES
(1, 9, 'POO'),
(1, 8, 'Implementare limbaj SQL'),
(1, 7, 'Matematica'),
(2, 5, 'POO'),
(2, 4, 'Implementare limbaj SQL'),
(2, 3, 'Matematica'),
(2, 6, 'Fizica'),
(2, 7, 'Informatica'),
(3, 10, 'POO'),
(3, 9, 'Programare procedurala'),
(3, 8, 'Matematica'),
(3, 7, 'Informatica'),
(3, 6, 'Fizica'),
(3, 9, 'Limba si literatura romana'),
(4, 2, 'POO'),
(4, 3, 'Matematica'),
(5, 8, 'POO'),
(5, 7, 'Programare procedurala'),
(5, 9, 'Matematica'),
(5, 6, 'Informatica'),
(5, 8, 'Fizica'),
(6, 9, 'POO'),
(6, 8, 'Programare procedurala'),
(6, 7, 'Matematica'),
(7, 3, 'POO'),
(7, 2, 'Programare procedurala'),
(7, 4, 'Matematica'),
(7, 3, 'Fizica'),
(8, 10, 'POO'),
(8, 9, 'Implementare limbaj SQL'),
(8, 10, 'Matematica'),
(8, 8, 'Informatica'),
(8, 7, 'Fizica'),
(9, 4, 'POO'),
(9, 3, 'Programare procedurala'),
(10, 7, 'POO'),
(10, 8, 'Implementare limbaj SQL'),
(10, 6, 'Matematica'),
(10, 7, 'Fizica'),
(10, 5, 'Informatica'),
(11, 9, 'Programare vizuala'),
(11, 8, 'POO'),
(11, 9, 'Matematica'),
(12, 2, 'Programare vizuala'),
(12, 3, 'POO'),
(12, 2, 'Matematica'),
(12, 4, 'Fizica'),
(12, 1, 'Informatica'),
(13, 8, 'Programare aplicatii mobile'),
(13, 9, 'POO'),
(13, 7, 'Matematica'),
(13, 8, 'Informatica'),
(13, 6, 'Limba si literatura romana'),
(14, 4, 'Programare vizuala'),
(14, 3, 'POO'),
(15, 10, 'Programare aplicatii mobile'),
(15, 9, 'POO'),
(15, 10, 'Matematica'),
(15, 8, 'Limba si literatura romana'),
(15, 7, 'Fizica'),
(15, 9, 'Informatica'),
(16, 8, 'Administrare RC'),
(16, 7, 'Securitatea informatiei'),
(16, 9, 'Matematica'),
(17, 3, 'Administrare RC'),
(17, 2, 'Securitatea informatiei'),
(17, 4, 'Matematica'),
(17, 3, 'Limba si literatura romana'),
(17, 2, 'Fizica'),
(18, 9, 'Administrare RC'),
(18, 10, 'Securitatea informatiei'),
(19, 4, 'Administrare RC'),
(19, 3, 'Securitatea informatiei'),
(19, 5, 'Matematica'),
(19, 4, 'Fizica'),
(20, 7, 'Administrare RC'),
(20, 8, 'Securitatea informatiei'),
(20, 6, 'Matematica'),
(20, 7, 'Limba si literatura romana'),
(20, 9, 'Fizica'),
(21, 9, 'Dezvoltare aplicatii Web'),
(21, 8, 'Creare site Web'),
(21, 7, 'Matematica'),
(21, 9, 'Design UI/UX'),
(21, 8, 'Programare client-side web'),
(22, 4, 'Dezvoltare aplicatii Web'),
(22, 3, 'Creare site Web'),
(23, 8, 'Dezvoltare aplicatii Web'),
(23, 9, 'Programare client-side web'),
(23, 7, 'Matematica'),
(24, 2, 'Dezvoltare aplicatii Web'),
(24, 3, 'Creare site Web'),
(24, 2, 'Matematica'),
(24, 3, 'Fizica'),
(25, 10, 'Dezvoltare aplicatii Web'),
(25, 9, 'Programare client-side web'),
(25, 8, 'Matematica'),
(25, 10, 'Design UI/UX'),
(25, 7, 'Fizica'),
(26, 8, 'Bazele contabilitatii'),
(26, 9, 'Contabilitate fiscala'),
(26, 7, 'Matematica'),
(27, 3, 'Bazele contabilitatii'),
(27, 2, 'Contabilitate fiscala'),
(27, 4, 'Matematica'),
(27, 3, 'Marketing'),
(28, 9, 'Bazele contabilitatii'),
(28, 8, 'Contabilitate fiscala'),
(28, 10, 'Matematica'),
(28, 7, 'Economie aplicata'),
(28, 9, 'Marketing'),
(29, 4, 'Bazele contabilitatii'),
(29, 3, 'Contabilitate fiscala'),
(30, 7, 'Bazele contabilitatii'),
(30, 8, 'Contabilitate fiscala'),
(30, 6, 'Matematica'),
(30, 9, 'Economie aplicata'),
(30, 5, 'Marketing'),
(31, 9, 'Bazele contabilitatii'),
(31, 8, 'Macroeconomie'),
(31, 7, 'Matematica'),
(31, 9, 'Economie aplicata'),
(32, 2, 'Bazele contabilitatii'),
(32, 3, 'Macroeconomie'),
(33, 8, 'Contabilitate fiscala'),
(33, 7, 'Macroeconomie'),
(33, 9, 'Matematica'),
(33, 6, 'Economie aplicata'),
(33, 8, 'Marketing'),
(34, 4, 'Bazele contabilitatii'),
(34, 3, 'Contabilitate fiscala'),
(34, 5, 'Matematica'),
(35, 10, 'Bazele contabilitatii'),
(35, 9, 'Contabilitate fiscala'),
(35, 8, 'Matematica'),
(35, 10, 'Economie aplicata'),
(35, 7, 'Macroeconomie'),
(36, 9, 'Drept administrativ'),
(36, 8, 'Drept constitutional'),
(36, 7, 'Limba si literatura romana'),
(37, 3, 'Drept administrativ'),
(37, 2, 'Drept constitutional'),
(37, 4, 'Limba si literatura romana'),
(37, 3, 'Etica profesionala'),
(38, 8, 'Drept afaceri'),
(38, 9, 'Drept constitutional'),
(38, 7, 'Matematica'),
(38, 8, 'Psihologie sociala'),
(38, 9, 'Etica profesionala'),
(39, 4, 'Drept administrativ'),
(39, 3, 'Drept constitutional'),
(40, 10, 'Drept afaceri'),
(40, 9, 'Drept constitutional'),
(40, 8, 'Matematica'),
(40, 10, 'Etica profesionala'),
(40, 7, 'Limba si literatura romana'),
(41, 9, 'Implementare limbaj SQL'),
(41, 8, 'Administrare Web server'),
(41, 7, 'Matematica'),
(42, 3, 'Implementare limbaj SQL'),
(42, 2, 'Administrare Web server'),
(42, 4, 'Matematica'),
(42, 3, 'Securitatea informatiei'),
(43, 10, 'Implementare limbaj SQL'),
(43, 9, 'Administrare Web server'),
(43, 8, 'Matematica'),
(43, 10, 'Securitatea informatiei'),
(43, 9, 'Fizica'),
(44, 4, 'Implementare limbaj SQL'),
(44, 3, 'Administrare Web server'),
(45, 7, 'Implementare limbaj SQL'),
(45, 8, 'Administrare Web server'),
(45, 6, 'Matematica'),
(45, 7, 'Securitatea informatiei'),
(45, 9, 'Fizica'),
(46, 8, 'TIC'),
(46, 7, 'Dactilografiere computerizata'),
(46, 9, 'Matematica'),
(46, 6, 'Echipamente de birou'),
(47, 3, 'TIC'),
(47, 2, 'Dactilografiere computerizata'),
(48, 9, 'TIC'),
(48, 8, 'Dactilografiere computerizata'),
(48, 7, 'Matematica'),
(48, 9, 'Echipamente de birou'),
(48, 6, 'Fizica'),
(49, 2, 'TIC'),
(49, 3, 'Dactilografiere computerizata'),
(49, 2, 'Matematica'),
(50, 10, 'TIC'),
(50, 9, 'Dactilografiere computerizata'),
(50, 8, 'Matematica'),
(50, 10, 'Echipamente de birou'),
(50, 7, 'Fizica'),
(50, 9, 'Limba si literatura romana');


ALTER TABLE studenti DROP CONSTRAINT studenti_id_grupa_fkey;
ALTER TABLE studenti ADD CONSTRAINT studenti_id_grupa_fkey 
    FOREIGN KEY (id_grupa) REFERENCES grupe(id) ON DELETE CASCADE;

ALTER TABLE note DROP CONSTRAINT note_id_student_fkey;
ALTER TABLE note ADD CONSTRAINT note_id_student_fkey 
    FOREIGN KEY (id_student) REFERENCES studenti(id) ON DELETE CASCADE;
